title:            Savant Krishna
description:      My homepage 
url:              # Site url.
signoff:          Savant
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
baseurl:          /scribble

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /blog
    external:     false
  - name:         Email
    url:          mailto:mail@sksavant.me
    external:     true
  - name:         GitHub
    url:          http://github.com/sksavant
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
